### ISSUE TITLE
Try to update computer states_id information

### ISSUE THREAD

**Issue by x3rus** [AnatomicJC/glpi-client#1]
Hi,

I use you code to pull glpi and it's work very good :D ,  but when I try to update an entry I have a problem. I don't think the problem is with your class but how I use it :-/ . 

Can you give me an exemple , to use the updateObject method ? 

bellow How I tried ... 

``` python
update_info = {
        'Computer': [
                {
                        'id':'6793',
                        'states_id' : '16'
                }
        ]
}

retur_update=glpi.updateObjects(update_info)
```

> Error message : 
> Traceback (most recent call last):
>  File "glpi_update_and_wipe.py", line 81, in <module>
>   retur_update=glpi.updateObjects(update_info)
>  File "/home/tboutry/ownCloud/git/glpi-nwipe/glpi_client/XMLRPCClient.py", line 93, in call
>    called_module = getattr(self.server, module)
> TypeError: getattr(): attribute name must be string

Thanks for your help ...

**Comment by AnatomicJC** [comment]
Hi x3rus,

Sorry for this late reply, I just try this updateObject method and this is how to use it.

From python interpreter: call help(glpi.updateObjects)

This method returns:

```
Help on function updateObjects in module glpi_client.XMLRPCClient:
updateObjects(module='glpi', **kwargs)
Wrapper for GLPI webservices updateObjects method:
It could be a good idea to see method's reference page:
https://forge.indepnet.net/projects/webservices/wiki/GlpiupdateObjects

@param module: webservices module to call (default: glpi)
@type module: str
@param kwargs: options for updateObjects method:

        - fields: array, mandatory
        - help: bool, optional

@type kwargs: dict
```

fields is mandatory so you have to use my class like this:

```
update_info = {
        'Computer': [
                {
                        'id':'6793',
                        'states_id' : '16'
                }
        ]
}

retur_update=glpi.updateObjects(fields=update_info)
```
